import { ATOM_KEY_MAP } from '@/constants/atom'

import { AST_NODE_TYPE } from '../../ast'

export const CONVERT_MAP = {
  [ATOM_KEY_MAP.If]: AST_NODE_TYPE.IF_TEXT,
  [ATOM_KEY_MAP.ElseIf]: AST_NODE_TYPE.ELSE_IF_TEXT,
  [ATOM_KEY_MAP.Else]: AST_NODE_TYPE.ELSE_TEXT,
  [ATOM_KEY_MAP.IfEnd]: AST_NODE_TYPE.IF_END_TEXT,
  [ATOM_KEY_MAP.Try]: AST_NODE_TYPE.TRY_TEXT,
  [ATOM_KEY_MAP.Catch]: AST_NODE_TYPE.CATCH_TEXT,
  [ATOM_KEY_MAP.Finally]: AST_NODE_TYPE.FINALLY_TEXT,
  [ATOM_KEY_MAP.TryEnd]: AST_NODE_TYPE.TRY_END_TEXT,
  [ATOM_KEY_MAP.ForStep]: AST_NODE_TYPE.FOR_STEP_TEXT,
  [ATOM_KEY_MAP.ForDict]: AST_NODE_TYPE.FOR_DICT_TEXT,
  [ATOM_KEY_MAP.ForList]: AST_NODE_TYPE.FOR_LIST_TEXT,
  [ATOM_KEY_MAP.ForExcelContent]: AST_NODE_TYPE.FOR_EXCEL_CONTENT,
  [ATOM_KEY_MAP.ForBrowserSimilar]: AST_NODE_TYPE.FOR_BRO_SIMILAR,
  [ATOM_KEY_MAP.ForEnd]: AST_NODE_TYPE.FOR_END_TEXT,
  [ATOM_KEY_MAP.While]: AST_NODE_TYPE.WHILE_TEXT,
  [ATOM_KEY_MAP.Group]: AST_NODE_TYPE.GROUP_TEXT,
  [ATOM_KEY_MAP.GroupEnd]: AST_NODE_TYPE.GROUP_END_TEXT,
  [ATOM_KEY_MAP.CvImageExist]: AST_NODE_TYPE.IF_TEXT,
  [ATOM_KEY_MAP.FileExist]: AST_NODE_TYPE.IF_TEXT,
  [ATOM_KEY_MAP.FolderExist]: AST_NODE_TYPE.IF_TEXT,
  [ATOM_KEY_MAP.WindowExist]: AST_NODE_TYPE.IF_TEXT,
}
