export const AST_NODE_TYPE = {
  IF_TEXT: 'if',
  ELSE_IF_TEXT: 'elseif',
  ELSE_TEXT: 'else',
  IF_END_TEXT: 'ifend',
  WHILE_TEXT: 'while',
  FOR_STEP_TEXT: 'stepfor',
  FOR_DICT_TEXT: 'dictfor',
  FOR_LIST_TEXT: 'listfor',
  FOR_EXCEL_CONTENT: 'excelcontentfor',
  FOR_BRO_SIMILAR: 'borsimilarfor',
  FOR_END_TEXT: 'forend',
  TRY_TEXT: 'try',
  CATCH_TEXT: 'catch',
  FINALLY_TEXT: 'finally',
  TRY_END_TEXT: 'tryend',
  GROUP_TEXT: 'group',
  GROUP_END_TEXT: 'groupend',
}
