import './style.css'

export * from './components/Auth'
export * from './components/CodeEditor'
export * from './components/ColorPicker'
export * from './components/ConfigProvider'
export * from './components/HintIcon'
export * from './components/Icon'
export * from './components/Loading'
export * from './components/LoadingDots'
export * from './components/NiceModal'
export * from './components/RichTextEditor'
export * from './components/Sheet'
export * from './components/Splitter'
export * from './components/StarMotion'

export { default } from './install'
export * from './theme'

export { initI18next, useTranslation, TranslationComponent, LanguageText } from './utils/i18next'
export type { LanguageType, LanguageResource } from './utils/i18next'
