export type ProviderStatus = "ready" | "coming_soon"
export type ProviderAuthMode = "api_key" | "oauth" | "environment"
export type ProviderAdapter = "native" | "openai-compatible"

export type ProviderDefinition = {
  id: string
  name: string
  description: string
  badge: string
  accent: string
  surface: string
  popular: boolean
  status: ProviderStatus
  authMode: ProviderAuthMode
  adapter: ProviderAdapter
  supportsModel: boolean
  supportsBaseUrl: boolean
  requiresBaseUrl?: boolean
  supportsDisplayName?: boolean
  comingSoonNote?: string
}

export const PROVIDER_REGISTRY: ProviderDefinition[] = [
  {
    id: "openai",
    name: "OpenAI",
    description: "GPT-4.1、GPT-4o 以及相关 OpenAI 模型",
    badge: "OA",
    accent: "#111827",
    surface: "#f3f4f6",
    popular: true,
    status: "ready",
    authMode: "api_key",
    adapter: "native",
    supportsModel: true,
    supportsBaseUrl: true,
  },
  {
    id: "anthropic",
    name: "Anthropic",
    description: "Anthropic 提供的 Claude 系列模型",
    badge: "AN",
    accent: "#a16207",
    surface: "#fff7ed",
    popular: true,
    status: "ready",
    authMode: "api_key",
    adapter: "native",
    supportsModel: true,
    supportsBaseUrl: true,
  },
  {
    id: "google",
    name: "Google",
    description: "Google 提供的 Gemini 模型",
    badge: "G",
    accent: "#2563eb",
    surface: "#eff6ff",
    popular: true,
    status: "ready",
    authMode: "api_key",
    adapter: "native",
    supportsModel: true,
    supportsBaseUrl: true,
  },
  {
    id: "openrouter",
    name: "OpenRouter",
    description: "通过单一入口访问多家模型提供商",
    badge: "OR",
    accent: "#0f766e",
    surface: "#ecfeff",
    popular: true,
    status: "ready",
    authMode: "api_key",
    adapter: "native",
    supportsModel: true,
    supportsBaseUrl: true,
  },
  {
    id: "vercel",
    name: "Vercel AI Gateway",
    description: "统一接入 AI 模型并支持智能路由",
    badge: "VC",
    accent: "#111827",
    surface: "#f3f4f6",
    popular: true,
    status: "ready",
    authMode: "api_key",
    adapter: "native",
    supportsModel: true,
    supportsBaseUrl: true,
  },
  {
    id: "xai",
    name: "xAI",
    description: "xAI 提供的 Grok 系列模型",
    badge: "xA",
    accent: "#7c3aed",
    surface: "#f5f3ff",
    popular: true,
    status: "ready",
    authMode: "api_key",
    adapter: "native",
    supportsModel: true,
    supportsBaseUrl: true,
  },
  {
    id: "deepseek",
    name: "DeepSeek",
    description: "DeepSeek 推理与代码模型",
    badge: "DS",
    accent: "#1d4ed8",
    surface: "#eff6ff",
    popular: true,
    status: "ready",
    authMode: "api_key",
    adapter: "native",
    supportsModel: true,
    supportsBaseUrl: true,
  },
  {
    id: "azure",
    name: "Azure OpenAI",
    description: "Azure OpenAI 部署",
    badge: "AZ",
    accent: "#0369a1",
    surface: "#ecfeff",
    popular: false,
    status: "ready",
    authMode: "api_key",
    adapter: "native",
    supportsModel: true,
    supportsBaseUrl: true,
  },
  {
    id: "groq",
    name: "Groq",
    description: "低延迟推理模型托管服务",
    badge: "GR",
    accent: "#dc2626",
    surface: "#fef2f2",
    popular: false,
    status: "ready",
    authMode: "api_key",
    adapter: "native",
    supportsModel: true,
    supportsBaseUrl: true,
  },
  {
    id: "mistral",
    name: "Mistral",
    description: "Mistral 托管模型端点",
    badge: "MI",
    accent: "#ea580c",
    surface: "#fff7ed",
    popular: false,
    status: "ready",
    authMode: "api_key",
    adapter: "native",
    supportsModel: true,
    supportsBaseUrl: true,
  },
  {
    id: "moonshot",
    name: "Moonshot AI",
    description: "Kimi 系列模型与代码能力",
    badge: "MS",
    accent: "#6d28d9",
    surface: "#f5f3ff",
    popular: false,
    status: "ready",
    authMode: "api_key",
    adapter: "native",
    supportsModel: true,
    supportsBaseUrl: true,
  },
  {
    id: "minimax",
    name: "MiniMax",
    description: "MiniMax 托管模型服务",
    badge: "MM",
    accent: "#be123c",
    surface: "#fff1f2",
    popular: false,
    status: "ready",
    authMode: "api_key",
    adapter: "native",
    supportsModel: true,
    supportsBaseUrl: true,
  },
  {
    id: "z-ai",
    name: "Z.AI",
    description: "Z.AI / GLM 系列模型",
    badge: "ZA",
    accent: "#065f46",
    surface: "#ecfdf5",
    popular: false,
    status: "ready",
    authMode: "api_key",
    adapter: "native",
    supportsModel: true,
    supportsBaseUrl: true,
  },
  {
    id: "custom-openai-compatible",
    name: "自定义兼容接口",
    description: "接入任何 OpenAI-compatible API",
    badge: "CU",
    accent: "#4338ca",
    surface: "#eef2ff",
    popular: true,
    status: "ready",
    authMode: "api_key",
    adapter: "openai-compatible",
    supportsModel: true,
    supportsBaseUrl: true,
    requiresBaseUrl: true,
    supportsDisplayName: true,
  },
  {
    id: "github-copilot",
    name: "GitHub Copilot",
    description: "通过 GitHub 账号授权接入 Copilot 模型",
    badge: "GH",
    accent: "#111827",
    surface: "#f3f4f6",
    popular: true,
    status: "coming_soon",
    authMode: "oauth",
    adapter: "native",
    supportsModel: false,
    supportsBaseUrl: false,
    comingSoonNote: "这一接入方式需要 OAuth 授权流程，后续版本会补齐。",
  },
  {
    id: "amazon-bedrock",
    name: "Amazon Bedrock",
    description: "使用 AWS 凭证与区域配置接入 Bedrock",
    badge: "AWS",
    accent: "#92400e",
    surface: "#fffbeb",
    popular: false,
    status: "coming_soon",
    authMode: "environment",
    adapter: "native",
    supportsModel: false,
    supportsBaseUrl: false,
    comingSoonNote: "这一接入方式需要 AWS 凭证链、区域和环境配置，后续版本会补齐。",
  },
  {
    id: "google-vertex",
    name: "Google Vertex",
    description: "通过 Google Cloud / Vertex AI 访问模型",
    badge: "GV",
    accent: "#1d4ed8",
    surface: "#eff6ff",
    popular: false,
    status: "coming_soon",
    authMode: "environment",
    adapter: "native",
    supportsModel: false,
    supportsBaseUrl: false,
    comingSoonNote: "这一接入方式依赖 Google Cloud 项目与环境凭证，后续版本会补齐。",
  },
  {
    id: "ollama",
    name: "Ollama",
    description: "连接本地或远程 Ollama 服务",
    badge: "OL",
    accent: "#0f766e",
    surface: "#ecfeff",
    popular: false,
    status: "coming_soon",
    authMode: "environment",
    adapter: "native",
    supportsModel: false,
    supportsBaseUrl: false,
    comingSoonNote: "这一接入方式需要本地模型发现与更细的连接配置，后续版本会补齐。",
  },
  {
    id: "lmstudio",
    name: "LM Studio",
    description: "连接 LM Studio 的本地兼容接口",
    badge: "LM",
    accent: "#7c2d12",
    surface: "#fff7ed",
    popular: false,
    status: "coming_soon",
    authMode: "environment",
    adapter: "openai-compatible",
    supportsModel: false,
    supportsBaseUrl: false,
    comingSoonNote: "这一接入方式需要本地模型发现与更细的连接配置，后续版本会补齐。",
  },
]

const providerRegistryMap = new Map(PROVIDER_REGISTRY.map((provider) => [provider.id, provider]))

export function isProviderId(value: string): value is string {
  return providerRegistryMap.has(value)
}

export function getProviderDefinition(providerId: string) {
  return providerRegistryMap.get(providerId)
}

export function getProviderLabel(providerId: string) {
  return getProviderDefinition(providerId)?.name ?? providerId
}
