import type { StudioAssistantGroup, StudioCollaborationMode, StudioSessionDetail } from './types'

export const assistantGroups: StudioAssistantGroup[] = [
  {
    id: 'single',
    title: '单聊助手',
    assistants: [
      {
        id: 'office',
        name: '办公助手',
        badge: '办',
        status: '在线',
        sessions: [
          { id: 'office-briefing', title: '经营例会跟进', time: '刚刚' },
        ],
      },
      {
        id: 'finance',
        name: '财务助手',
        badge: '财',
        status: '运行中',
        sessions: [
          { id: 'finance-q3', title: '季度财务分析', time: '2 分钟前', active: true },
          { id: 'finance-batch', title: '报销单批量处理', time: '1 小时前' },
          { id: 'finance-check', title: '供应商对账核查', time: '昨天' },
        ],
      },
      {
        id: 'code',
        name: '代码助手',
        badge: '代',
        status: '待命',
        sessions: [
          { id: 'code-api', title: 'API 接口优化', time: '3 小时前' },
          { id: 'code-bug', title: 'Bug 修复追踪', time: '昨天' },
        ],
      },
      {
        id: 'data',
        name: '数据分析师',
        badge: '数',
        status: '待命',
        sessions: [
          { id: 'data-growth', title: '用户增长报告', time: '2 天前' },
        ],
      },
    ],
  },
  {
    id: 'collaboration',
    title: '群聊',
    assistants: [
      {
        id: 'audit-group',
        name: '年报审计协作',
        badge: '协',
        status: '群聊',
        tag: '群聊',
        groupCollaborationMode: 'auto',
        groupParticipantAssistantIds: ['finance', 'code'],
        sessions: [
          { id: 'audit-collab', title: '年报审计协作', time: '昨天' },
        ],
      },
    ],
  },
]

function participantDisplayName(id: string) {
  if (id === 'office')
    return '办公助手'
  if (id === 'finance')
    return '财务助手'
  if (id === 'code')
    return '代码助手'
  if (id === 'data')
    return '数据分析师'
  return id
}

function collaborationModeLabel(mode: StudioCollaborationMode) {
  if (mode === 'pipeline')
    return '流水线'
  if (mode === 'race')
    return '赛马'
  if (mode === 'debate')
    return '会审'
  return '自动'
}

export function createSessionDetailTemplate({
  sessionId,
  assistantId,
  assistantName,
  assistantBadge,
  sessionTitle,
  sessionTag,
  workspacePath,
  mode = 'regular',
  participantAssistantIds = [],
  coordinatorAssistantId,
  collaborationMode = 'auto',
}: {
  sessionId: string
  assistantId: string
  assistantName: string
  assistantBadge: string
  sessionTitle: string
  sessionTag: string
  workspacePath?: string
  mode?: 'regular' | 'group'
  participantAssistantIds?: string[]
  coordinatorAssistantId?: string
  collaborationMode?: StudioCollaborationMode
}): StudioSessionDetail {
  const resolvedWorkspacePath = workspacePath || `~/Projects/${assistantId}/${sessionId}`

  if (mode === 'group') {
    const participants = [...new Set(participantAssistantIds.filter(id => id))]
    const resolvedParticipants = participants.length > 0 ? participants : ['finance', 'code']
    const coordinatorId = coordinatorAssistantId || 'coordinator'
    const modeLabel = collaborationModeLabel(collaborationMode)
    const participantText = resolvedParticipants.map(participantDisplayName).join('、')

    return {
      id: sessionId,
      mode: 'group',
      headerTitle: sessionTitle,
      headerTag: '群聊',
      headerBadge: '协',
      assistantName: '主 Agent',
      participantAssistantIds: resolvedParticipants,
      coordinatorAssistantId: coordinatorId,
      collaborationMode,
      collaborationState: 'planning',
      clarificationOwner: 'coordinator',
      collaborationSummary: {
        activeTasks: 2,
        completedTasks: 0,
        blockedTasks: 0,
      },
      run: {
        id: `run-${sessionId}`,
        status: 'running',
        label: '处理中',
        summary: `主 Agent 正在按「${modeLabel}」模式编排协作任务。`,
      },
      promptTitle: '建议追问',
      options: [
        { id: 'summary', title: '同步当前协作结论', description: '让主 Agent 输出阶段结论和剩余风险。' },
        { id: 'plan', title: '更新协作计划优先级', description: '按最新目标重排子任务执行顺序。' },
      ],
      confirmLabel: '发起协作',
      inputPlaceholder: '描述目标，主 Agent 会先澄清关键边界，再调度参与助手…',
      attachments: [],
      workspacePath: resolvedWorkspacePath,
      messages: [
        {
          id: `${sessionId}-user`,
          role: 'user',
          content: `发起群聊协作：请 ${participantText} 一起完成“${sessionTitle}”。`,
          order: 0,
        },
      ],
      chatCards: [
        {
          id: `${sessionId}-coordinator-intake`,
          type: 'text',
          assistantId: coordinatorId,
          assistantName: '主 Agent',
          assistantBadge: '主',
          time: '刚刚',
          order: 1,
          content: `收到。我会先作为主协调者接管澄清与分发，并采用「${modeLabel}」协作模式推进。`,
        },
        {
          id: `${sessionId}-coordinator-plan`,
          type: 'plan',
          assistantId: coordinatorId,
          assistantName: '主 Agent',
          assistantBadge: '主',
          time: '刚刚',
          order: 2,
          title: '协作执行计划',
          description: '主 Agent 负责接待、澄清、分发与汇总，不直接执行子任务。',
          steps: [
            { id: `${sessionId}-plan-intake`, title: '主 Agent 对齐需求与边界', status: 'done' },
            { id: `${sessionId}-plan-dispatch`, title: `分发任务给：${participantText}`, status: 'running' },
            { id: `${sessionId}-plan-converge`, title: '汇总多助手结果并输出结论', status: 'pending' },
          ],
        },
        {
          id: `${sessionId}-coordinator-tools`,
          type: 'tool-call-list',
          assistantId: coordinatorId,
          assistantName: '主 Agent',
          assistantBadge: '主',
          time: '刚刚',
          order: 3,
          summary: '主 Agent 正在触发多助手协作流程。',
          calls: [
            { name: 'classify_intent', arg: 'user-request', status: 'done', detail: '识别任务目标和约束边界。' },
            { name: 'dispatch_participants', arg: resolvedParticipants.join(','), status: 'running', detail: '分发子任务并等待回传。' },
          ],
        },
      ],
      workspaceFiles: [
        { id: `${sessionId}-root`, name: resolvedWorkspacePath, type: 'folder', indent: 0, expanded: true },
        { id: `${sessionId}-plan`, name: 'group-plan.md', type: 'file', indent: 1, highlighted: true, status: '协作中' },
        { id: `${sessionId}-handoff`, name: 'coordination-summary.md', type: 'file', indent: 1, status: '待更新' },
      ],
      artifacts: [
        { id: `${sessionId}-artifact-plan`, name: 'group-plan.md', summary: `主 Agent ${modeLabel}协作计划与分工。`, tag: '协作中', tagTone: 'primary' },
        { id: `${sessionId}-artifact-summary`, name: 'coordination-summary.md', summary: '协作中间结论与待确认事项。', tag: '待更新', tagTone: 'neutral' },
      ],
    }
  }

  return {
    id: sessionId,
    mode: 'regular',
    headerTitle: sessionTitle,
    headerTag: sessionTag,
    headerBadge: assistantBadge,
    assistantName,
    promptTitle: '继续当前会话',
    promptDescription: '把常见下一步建议放在回复末尾，减少反复组织语言。',
    options: [
      { id: 'summary', title: '总结当前进展', description: '快速回看当前会话已经完成了什么。' },
      { id: 'report', title: '输出结构化结果', description: '整理成可分享的报告、纪要或摘要。' },
    ],
    confirmLabel: '开始处理',
    inputPlaceholder: '输入消息，或使用 / 调用技能、@ 提及助手…',
    attachments: [],
    workspacePath: resolvedWorkspacePath,
    messages: [
      {
        id: `${sessionId}-user`,
        role: 'user',
        content: `帮我处理一下“${sessionTitle}”这个任务。`,
      },
      {
        id: `${sessionId}-assistant`,
        role: 'assistant',
        assistantName,
        time: '刚刚',
        content: '收到，我会先梳理任务上下文，再输出建议和可交付结果。',
      },
    ],
    chatCards: [
      {
        id: `${sessionId}-thinking`,
        type: 'thinking',
        assistantId,
        assistantName,
        assistantBadge,
        time: '刚刚',
        title: '正在思考',
        description: `${assistantName}正在读取当前任务上下文，并准备生成第一版执行方案。`,
      },
      {
        id: `${sessionId}-tooling`,
        type: 'tool-call-list',
        assistantId,
        assistantName,
        assistantBadge,
        time: '刚刚',
        summary: `${assistantName}正在读取工作区并整理当前任务需要的基础信息。`,
        calls: [
          { name: 'read_workspace', arg: `~/Projects/${assistantId}`, status: 'done' },
          { name: 'compose_plan', arg: sessionTitle, status: 'running' },
        ],
      },
      {
        id: `${sessionId}-text`,
        type: 'text',
        assistantId,
        assistantName,
        assistantBadge,
        time: '刚刚',
        content: '当前是新会话草稿，后续会根据后端真实接口返回替换成完整消息流和工作区结果。',
      },
    ],
    workspaceFiles: [
      { id: `${sessionId}-root`, name: resolvedWorkspacePath, type: 'folder', indent: 0, expanded: true },
      { id: `${sessionId}-note`, name: 'task-note.md', type: 'file', indent: 1, highlighted: true, status: '生成中' },
    ],
    artifacts: [
      { id: `${sessionId}-artifact`, name: 'task-note.md', summary: '当前会话的任务记录与阶段产出。', tag: '生成中', tagTone: 'primary' },
    ],
  }
}

export const sessionDetails: Record<string, StudioSessionDetail> = {
  'office-briefing': {
    promptTitle: '你还可以继续这样推进',
    promptDescription: '基于当前结果，继续补齐缺口或直接生成下一步产物。',
    options: [
      { id: 'summary', title: '要不要先帮你总结这轮进展？', description: '回看 recap、待办和邮件草稿的完成状态。' },
      { id: 'todo', title: '要不要把当前结果整理成待办清单？', description: '整理当前 action items 和负责人分配。' },
      { id: 'finance', title: '要不要让财务助手一起复核？', description: '补充财务视角的风险和数据口径。' },
    ],
    id: 'office-briefing',
    mode: 'regular',
    headerTitle: '经营例会跟进',
    headerTag: '处理中',
    headerBadge: '办',
    assistantName: '办公助手',
    confirmLabel: '继续执行',
    inputPlaceholder: '补充会议背景、希望强调的风险或需要同步给谁，我会继续完善 recap 和 follow-up。',
    attachments: ['meeting-notes.md', 'sales-weekly.xlsx'],
    workspacePath: '~/Projects/office/ops-briefing',
    workspacePreview: {
      kind: 'table',
      fileName: 'ops_follow_up_table.md',
      status: '已生成',
      title: '经营例会跟进行动表',
      description: '根据会议纪要与周报整理出的负责人、截止时间和当前状态。',
      columns: ['事项', '负责人', '截止时间', '状态'],
      rows: [
        { id: 'ops-row-1', cells: ['补齐华东区签约预测', '销售负责人', '今天 18:00', '进行中'] },
        { id: 'ops-row-2', cells: ['确认交付资源排期', '交付负责人', '明天 12:00', '待办'] },
        { id: 'ops-row-3', cells: ['更新经营周报摘要', 'CEO 助理', '明天 09:00', '已同步'], tone: 'success' },
      ],
    },
    messages: [
      {
        id: 'office-briefing-user',
        role: 'user',
        content: '帮我整理明早经营例会的重点，并把会后 follow-up、待办和邮件草稿一起准备好。',
      },
    ],
    chatCards: [
      {
        id: 'office-context',
        type: 'context-scope',
        assistantId: 'office',
        assistantName: '办公助手',
        assistantBadge: '办',
        time: '刚刚',
        title: '任务上下文已对齐',
        description: '我会先汇总本周经营变化、会议纪要和跟进动作，再输出 recap、待办清单和发送草稿。',
        fields: [
          { label: '工作目标', value: '形成明早经营例会简报与会后跟进动作' },
          { label: '时间范围', value: '最近 7 天经营变化与今日会议纪要' },
          { label: '输出形式', value: '会议 recap、行动表、邮件草稿' },
          { label: '当前假设', value: '优先同步销售与交付风险，不自动外发' },
        ],
        tags: ['会议', '周报', '跟进'],
      },
      {
        id: 'office-sources',
        type: 'knowledge-sources',
        assistantId: 'office',
        assistantName: '办公助手',
        assistantBadge: '办',
        time: '刚刚',
        title: '已纳入上下文',
        description: '当前可以直接使用本地附件、会议纪要和已连接工作区数据。',
        sources: [
          { id: 'office-source-1', label: 'meeting-notes.md', type: 'file', status: 'retrieved', detail: '已读取经营例会纪要与待确认事项' },
          { id: 'office-source-2', label: 'sales-weekly.xlsx', type: 'file', status: 'retrieved', detail: '已汇总本周新增签约、流失与预测变化' },
          { id: 'office-source-3', label: '企业微信会议纪要', type: 'connector', status: 'indexed', detail: '已索引最近 3 次经营会纪要' },
          { id: 'office-source-4', label: 'CRM 商机看板', type: 'connector', status: 'needs-auth', detail: '需要授权后才能读取负责人和阶段变化' },
        ],
      },
      {
        id: 'office-connect',
        type: 'connect-auth',
        assistantId: 'office',
        assistantName: '办公助手',
        assistantBadge: '办',
        time: '刚刚',
        title: '继续前需要连接 CRM',
        description: '为了补齐商机负责人和预计签约时间，需要读取 CRM 中本周的阶段变化。',
        provider: 'Salesforce',
        statusTag: '待授权',
        scopes: ['读取商机阶段', '读取负责人', '读取预计签约时间'],
        actions: [
          { id: 'office-connect-later', label: '稍后处理', tone: 'ghost' },
          { id: 'office-connect-now', label: '连接 CRM', tone: 'primary' },
        ],
      },
      {
        id: 'office-boundary',
        type: 'error-boundary',
        assistantId: 'office',
        assistantName: '办公助手',
        assistantBadge: '办',
        time: '刚刚',
        title: '日历权限不足',
        description: '当前账号无法读取 CEO 私有日程，我会先基于公开纪要和附件继续整理。',
        severity: 'warning',
        blockedBy: 'Calendar private events scope',
        suggestions: [
          '先使用公开会议纪要完成 briefing 与 action items。',
          '如需自动排会，请由管理员补充共享权限后再执行。',
        ],
        actions: [
          { id: 'office-boundary-continue', label: '继续现有信息', tone: 'soft' },
          { id: 'office-boundary-request', label: '申请权限', tone: 'secondary' },
        ],
      },
      {
        id: 'office-param',
        type: 'param-form',
        assistantId: 'office',
        assistantName: '办公助手',
        assistantBadge: '办',
        time: '刚刚',
        title: '补齐会后跟进口径',
        description: '为了自动生成待办，请确认跟进截止时间和优先同步方向。',
        confirmLabel: '提交参数',
        fields: [
          { id: 'deadline', label: '统一截止日期', required: true, type: 'date' },
          {
            id: 'focus',
            label: '优先同步方向',
            type: 'choice',
            choices: [
              { id: 'sales', label: '销售风险' },
              { id: 'delivery', label: '交付排期' },
              { id: 'all', label: '全部同步' },
            ],
          },
        ],
      },
      {
        id: 'office-plan',
        type: 'plan',
        assistantId: 'office',
        assistantName: '办公助手',
        assistantBadge: '办',
        time: '刚刚',
        title: '执行计划',
        description: '把这轮任务拆成四步，方便你快速判断 Agent 当前处理到了哪里。',
        steps: [
          { id: 'office-plan-1', title: '汇总会议纪要与周报', description: '整理经营变化、异常项和负责人', status: 'done' },
          { id: 'office-plan-2', title: '补齐 CRM 商机状态', description: '等待连接 CRM 后完善负责人和预计签约时间', status: 'running' },
          { id: 'office-plan-3', title: '生成 recap 与 action items', description: '输出会议摘要、行动表和邮件草稿', status: 'pending' },
          { id: 'office-plan-4', title: '确认是否创建定时跟进', description: '根据用户确认生成自动追踪任务', status: 'pending' },
        ],
      },
      {
        id: 'office-tools',
        type: 'tool-call-list',
        assistantId: 'office',
        assistantName: '办公助手',
        assistantBadge: '办',
        time: '刚刚',
        summary: '办公助手正在读取附件、整理纪要，并补齐会后跟进所需的关键信息。',
        calls: [
          {
            name: 'read_file',
            arg: 'meeting-notes.md',
            status: 'done',
            duration: '0.8s',
            detail: '提取会议纪要中的结论、负责人和风险项。',
            result: '已识别 8 条关键决策、3 个待确认事项。',
            steps: ['解析本地 Markdown 文件', '提取责任人与截止时间', '合并为结构化纪要摘要'],
          },
          {
            name: 'read_file',
            arg: 'sales-weekly.xlsx',
            status: 'done',
            duration: '1.2s',
            detail: '补充销售周报中的商机状态与跟进负责人。',
            result: '发现 2 个重点商机尚未指定 owner。',
            steps: ['读取销售线索表', '比对周会结论', '标记缺失字段'],
          },
          {
            name: 'compose_briefing',
            arg: 'ops_meeting_recap.md',
            status: 'running',
            detail: '正在生成对内 recap 和 follow-up 动作清单。',
            steps: ['汇总会议结论', '生成行动项表', '同步到工作空间产物'],
          },
          {
            name: 'draft_followup_email',
            arg: 'follow-up-email.eml',
            status: 'pending',
            detail: '等待 recap 完成后生成外发邮件草稿。',
            steps: ['引用 recap 重点', '生成收件人摘要', '追加下一次检查节点'],
          },
        ],
      },
      {
        id: 'office-citations',
        type: 'citation-list',
        assistantId: 'office',
        assistantName: '办公助手',
        assistantBadge: '办',
        time: '刚刚',
        title: '关键依据',
        description: '后续接真实 Agent 时，这一类卡片用于映射 research / connector / 引用来源。',
        citations: [
          { id: 'office-citation-1', title: '经营例会纪要', excerpt: '华东区本周新增签约低于预测 18%，需要重新评估月底目标。', source: 'meeting-notes.md', meta: '09:20' },
          { id: 'office-citation-2', title: '销售周报', excerpt: '本周新增重点商机 6 个，其中 2 个仍缺负责人确认。', source: 'sales-weekly.xlsx', meta: '最新同步' },
        ],
      },
      {
        id: 'office-meeting',
        type: 'meeting-recap',
        assistantId: 'office',
        assistantName: '办公助手',
        assistantBadge: '办',
        time: '刚刚',
        title: '会议纪要摘要',
        description: '已整理出本次经营会确认结论、待确认问题和会后动作。',
        participants: ['CEO 助理', '销售负责人', '交付负责人'],
        decisions: [
          '优先跟进华东区签约预测偏差，并补齐负责人确认。',
          '交付排期在明天中午前回收最新资源占用情况。',
        ],
        openQuestions: [
          'CRM 中 2 个重点商机尚未补全预计签约时间。',
        ],
        actionItems: [
          { id: 'office-action-1', title: '补齐华东区重点商机预测', owner: '销售负责人', due: '今天 18:00', status: 'in-progress' },
          { id: 'office-action-2', title: '确认交付资源排期', owner: '交付负责人', due: '明天 12:00', status: 'todo' },
        ],
      },
      {
        id: 'office-work-items',
        type: 'work-item-list',
        assistantId: 'office',
        assistantName: '办公助手',
        assistantBadge: '办',
        time: '刚刚',
        title: '待办事项',
        description: '这类卡片对应 Planner / Tasks / 会后 follow-up 等工作实体。',
        items: [
          { id: 'office-task-1', title: '同步华东区签约预测差异', owner: '销售负责人', due: '今天 18:00', detail: '补齐负责人、阶段变化和预测金额', status: 'in-progress' },
          { id: 'office-task-2', title: '更新经营周报摘要', owner: 'CEO 助理', due: '明天 09:00', detail: '会议 recap、风险提醒和责任人同步到周报', status: 'todo' },
          { id: 'office-task-3', title: '确认交付资源排期', owner: '交付负责人', due: '明天 12:00', detail: '补充资源冲突与缓解方案', status: 'blocked' },
        ],
      },
      {
        id: 'office-schedule',
        type: 'schedule',
        assistantId: 'office',
        assistantName: '办公助手',
        assistantBadge: '办',
        time: '刚刚',
        title: '已建议自动跟进',
        description: '如果你确认，我可以在每个工作日自动汇总经营变化并提醒负责人。',
        scheduleLabel: '工作日 18:00 自动汇总销售与交付变更',
        nextRun: '明天 18:00',
        deliveryChannel: '企业微信 + 邮件',
        statusTag: '建议创建',
        actions: [
          { id: 'office-schedule-skip', label: '暂不创建', tone: 'ghost' },
          { id: 'office-schedule-create', label: '创建定时任务', tone: 'primary' },
        ],
      },
      {
        id: 'office-draft',
        type: 'draft-review',
        assistantId: 'office',
        assistantName: '办公助手',
        assistantBadge: '办',
        time: '刚刚',
        title: '跟进邮件草稿',
        description: '这一类卡片用于展示待发送的邮件、通知或文档草稿。',
        draftKind: 'email',
        subject: '经营例会后续跟进与负责人确认',
        recipients: ['销售负责人', '交付负责人', 'CEO 助理'],
        sections: [
          { label: '会议结论', value: '华东区签约预测偏差需要在今天下班前重新确认。' },
          { label: '风险提醒', value: '2 个重点商机仍缺预计签约时间，影响月底经营判断。' },
          { label: '需要确认', value: '请销售与交付分别补齐负责人和资源排期。' },
        ],
        actions: [
          { id: 'office-draft-edit', label: '继续修改', tone: 'secondary' },
          { id: 'office-draft-send', label: '直接发送', tone: 'primary' },
        ],
      },
      {
        id: 'office-artifact',
        type: 'artifact-preview',
        assistantId: 'office',
        assistantName: '办公助手',
        assistantBadge: '办',
        time: '刚刚',
        preview: {
          kind: 'table',
          fileName: 'ops_follow_up_table.md',
          status: '已生成',
          tag: '行动表',
          title: '经营例会跟进行动表',
          description: '表格预览用于映射任务、审批列表、汇总清单等结构化产物。',
          columns: ['事项', '负责人', '截止时间', '状态'],
          rows: [
            { id: 'office-preview-row-1', cells: ['补齐华东区签约预测', '销售负责人', '今天 18:00', '进行中'] },
            { id: 'office-preview-row-2', cells: ['确认交付资源排期', '交付负责人', '明天 12:00', '待办'] },
            { id: 'office-preview-row-3', cells: ['更新经营周报摘要', 'CEO 助理', '明天 09:00', '已同步'], tone: 'success' },
          ],
        },
      },
      {
        id: 'office-approval',
        type: 'approval',
        assistantId: 'office',
        assistantName: '办公助手',
        assistantBadge: '办',
        time: '刚刚',
        title: '发送并创建任务',
        description: '是否允许我发送跟进邮件，并同步创建 3 条待办到任务中心？',
        levelTag: '外发动作',
        actions: [
          { id: 'office-approval-reject', label: '先不要', tone: 'ghost' },
          { id: 'office-approval-allow', label: '允许执行', tone: 'primary' },
          { id: 'office-approval-always', label: '始终允许', tone: 'soft' },
        ],
      },
      {
        id: 'office-text',
        type: 'text',
        assistantId: 'office',
        assistantName: '办公助手',
        assistantBadge: '办',
        time: '刚刚',
        tone: 'subtle',
        content: '上面这组卡片覆盖了办公助手在真实 Agent 工作流里最常见的上下文、连接、进度、引用、产物、审批与任务型消息。',
      },
    ],
    workspaceFiles: [
      { id: 'office-root', name: '~/Projects/office/ops-briefing', type: 'folder', indent: 0, expanded: true },
      { id: 'office-meeting-notes', name: 'meeting-notes.md', type: 'file', indent: 1, status: '已读取' },
      { id: 'office-sales-weekly', name: 'sales-weekly.xlsx', type: 'file', indent: 1, status: '已读取' },
      { id: 'office-follow-up-table', name: 'ops_follow_up_table.md', type: 'file', indent: 1, highlighted: true, status: '已生成' },
      { id: 'office-follow-up-email', name: 'follow-up-email.eml', type: 'file', indent: 1, status: '待确认' },
    ],
    artifacts: [
      { id: 'office-artifact-1', name: 'ops_follow_up_table.md', summary: '经营例会会后行动表与负责人、截止时间汇总。', tag: '已生成', tagTone: 'primary' },
      { id: 'office-artifact-2', name: 'follow-up-email.eml', summary: '会后同步邮件草稿，待用户确认是否发送。', tag: '待确认', tagTone: 'neutral' },
      { id: 'office-artifact-3', name: 'ops_meeting_recap.md', summary: '经营例会 recap 与风险摘要。', tag: '更新中', tagTone: 'primary' },
    ],
  },
  'finance-q3': {
    id: 'finance-q3',
    mode: 'regular',
    headerTitle: '季度财务分析',
    headerTag: '运行中',
    headerBadge: '财',
    assistantName: '财务助手',
    confirmLabel: '确认选择',
    inputPlaceholder: '输入消息，或使用 / 调用技能、@ 提及助手…',
    attachments: ['Q3_finance_data.xlsx'],
    workspacePath: '~/Documents/Q3财务分析',
    chartTitle: '各部门预算执行率 Q3',
    chartRows: [
      { label: '研发部', value: 87 },
      { label: '市场部', value: 100, over: true },
      { label: '运营部', value: 73 },
      { label: '人事部', value: 95 },
    ],
    workspacePreview: {
      kind: 'chart',
      fileName: 'budget_chart.js',
      status: '生成中',
      title: '各部门预算执行率 Q3',
      chartRows: [
        { label: '研发部', value: 87 },
        { label: '市场部', value: 100, over: true },
        { label: '运营部', value: 73 },
        { label: '人事部', value: 95 },
      ],
    },
    messages: [
      {
        id: 'finance-q3-user',
        role: 'user',
        content: '帮我分析一下 Q3 的财务数据，重点看一下各部门的预算执行情况，并生成一份可视化报告。',
      },
    ],
    chatCards: [
      {
        id: 'finance-q3-thinking',
        type: 'thinking',
        assistantId: 'finance',
        assistantName: '财务助手',
        assistantBadge: '财',
        time: '刚刚',
        title: '正在思考',
        description: '按部门汇总 Q3 数据，读取财务文件，计算预算执行率，并生成可视化代码。',
      },
      {
        id: 'finance-q3-tools',
        type: 'tool-call-list',
        assistantId: 'finance',
        assistantName: '财务助手',
        assistantBadge: '财',
        time: '刚刚',
        calls: [
          {
            name: 'read_file',
            arg: 'Q3_finance_data.xlsx',
            status: 'done',
            duration: '1.1s',
            detail: '读取预算、执行率与部门差异数据。',
            result: '已汇总 6 个部门、24 条预算明细。',
            steps: ['定位财务源文件', '抽取预算字段', '归并异常波动项'],
          },
          {
            name: 'generate_chart',
            arg: 'budget_chart.js',
            status: 'running',
            detail: '正在生成预算执行率图表与超支提示。',
            steps: ['计算部门执行率', '标记超支部门', '输出图表配置'],
          },
        ],
      },
      {
        id: 'finance-q3-options',
        type: 'choice-form',
        assistantId: 'finance',
        assistantName: '财务助手',
        assistantBadge: '财',
        time: '刚刚',
        title: '你希望我怎样处理这份数据？',
        description: '请选择一种分析方式',
        confirmLabel: '确认选择',
        options: [
          { id: 'dept', label: '按部门汇总分析', description: '将所有数据按部门聚合，生成对比报告' },
          { id: 'trend', label: '按时间维度趋势分析', description: '展示各月度、季度走势，识别异常波动' },
          { id: 'anomaly', label: '聚焦异常项目排查', description: '仅关注超预算或负增长的项目' },
          { id: 'export', label: '全量明细导出', description: '原始数据导出为 Excel，人工核查' },
        ],
      },
      {
        id: 'finance-q3-preview',
        type: 'artifact-preview',
        assistantId: 'finance',
        assistantName: '财务助手',
        assistantBadge: '财',
        time: '刚刚',
        fileName: 'budget_chart.js',
        tag: '生成中',
        previewTitle: '各部门预算执行率 Q3',
        chartRows: [
          { label: '研发部', value: 87 },
          { label: '市场部', value: 100, over: true },
          { label: '运营部', value: 73 },
          { label: '人事部', value: 95 },
        ],
        legend: [
          { label: '正常', color: '#726FFF' },
          { label: '超支', color: '#EF4444' },
        ],
      },
      {
        id: 'finance-q3-text',
        type: 'text',
        assistantId: 'finance',
        assistantName: '财务助手',
        assistantBadge: '财',
        time: '刚刚',
        content: '图表已生成。市场部预算执行率最高，已达到预警阈值。我会继续补齐完整分析报告。',
      },
    ],
    workspaceFiles: [
      { id: 'finance-root', name: '~/Documents/Q3财务分析', type: 'folder', indent: 0, expanded: true },
      { id: 'finance-data', name: 'Q3_finance_data.xlsx', type: 'file', indent: 1, status: '已读取' },
      { id: 'finance-chart', name: 'budget_chart.js', type: 'file', indent: 1, highlighted: true, status: '生成中' },
      { id: 'finance-report', name: 'Q3_analysis_report.md', type: 'file', indent: 1, status: '生成中' },
    ],
    artifacts: [
      { id: 'finance-chart-artifact', name: 'budget_chart.js', summary: '实时生成的工作区结果预览。', tag: '生成中', tagTone: 'primary' },
      { id: 'finance-file-artifact', name: 'Q3_finance_data.xlsx', summary: '原始数据文件已读取。', tag: '已读取', tagTone: 'neutral' },
      { id: 'finance-report-artifact', name: 'Q3_analysis_report.md', summary: '分析报告正在生成。', tag: '生成中', tagTone: 'primary' },
    ],
  },
  'finance-batch': createSessionDetailTemplate({
    sessionId: 'finance-batch',
    assistantId: 'finance',
    assistantName: '财务助手',
    assistantBadge: '财',
    sessionTitle: '报销单批量处理',
    sessionTag: '待命',
  }),
  'finance-check': createSessionDetailTemplate({
    sessionId: 'finance-check',
    assistantId: 'finance',
    assistantName: '财务助手',
    assistantBadge: '财',
    sessionTitle: '供应商对账核查',
    sessionTag: '待命',
  }),
  'code-api': {
    promptTitle: '继续接口优化会话',
    promptDescription: '把常见下一步建议放在回复末尾，方便继续推进优化。',
    options: [
      { id: 'summary', title: '总结优化结论', description: '归纳当前瓶颈、方案和风险。' },
      { id: 'patch', title: '输出补丁建议', description: '整理成可落地的改动建议。' },
    ],
    id: 'code-api',
    mode: 'regular',
    headerTitle: 'API 接口优化',
    headerTag: '处理中',
    headerBadge: '代',
    assistantName: '代码助手',
    confirmLabel: '提交方案',
    inputPlaceholder: '继续补充接口瓶颈、目标耗时或希望优先优化的链路…',
    attachments: ['trace-report.json', 'api-benchmark.md'],
    workspacePath: '~/Projects/web-app/src/services/api',
    workspacePreview: {
      kind: 'code',
      fileName: 'api-performance.patch.ts',
      status: '更新中',
      title: '接口响应时间优化方案',
      language: 'ts',
      code: `export async function requestWithCache(key: string, request: () => Promise<any>) {\n  const hit = responseCache.get(key)\n  if (hit) return hit\n\n  const result = await request()\n  responseCache.set(key, result, 15_000)\n  return result\n}\n\nexport function normalizeRequestPayload(payload: Record<string, unknown>) {\n  return Object.fromEntries(Object.entries(payload).filter(([, value]) => value !== undefined))\n}`,
    },
    messages: [
      {
        id: 'code-api-user',
        role: 'user',
        content: '帮我梳理一下 API 接口响应慢的问题，先给出一版接口响应时间优化方案。',
      },
    ],
    chatCards: [
      {
        id: 'code-api-thinking',
        type: 'thinking',
        assistantId: 'code',
        assistantName: '代码助手',
        assistantBadge: '代',
        time: '3 小时前',
        title: '正在思考',
        description: '先定位高耗时链路，再拆分缓存、序列化和重复请求三个优化方向。',
      },
      {
        id: 'code-api-tools',
        type: 'tool-call-list',
        assistantId: 'code',
        assistantName: '代码助手',
        assistantBadge: '代',
        time: '3 小时前',
        summary: '代码助手正在扫描 API 请求封装和上游数据整理逻辑。',
        calls: [
          {
            name: 'scan_request_layer',
            arg: 'src/services/api',
            status: 'done',
            duration: '1.4s',
            detail: '扫描请求层封装、重试逻辑与缓存命中策略。',
            result: '识别出 3 处可合并的重复请求封装。',
            steps: ['遍历接口目录', '识别重复请求链路', '标记串行等待点'],
          },
          {
            name: 'profile_slow_routes',
            arg: '/api/user/list, /api/report/summary',
            status: 'done',
            duration: '2.6s',
            detail: '采样慢接口的序列化和渲染耗时。',
            result: '首个接口 620ms 为缓存缺失，第二个接口 410ms 为重复反序列化。',
            steps: ['抓取慢接口样本', '拆分耗时段', '定位瓶颈模块'],
          },
          {
            name: 'compose_patch',
            arg: 'api-performance.patch.ts',
            status: 'running',
            detail: '正在生成请求去重和缓存回填补丁。',
            steps: ['合并请求层工具函数', '补充缓存命中分支', '准备回归说明'],
          },
        ],
      },
      {
        id: 'code-api-text',
        type: 'text',
        assistantId: 'code',
        assistantName: '代码助手',
        assistantBadge: '代',
        time: '3 小时前',
        content: '首轮结论是：重复请求去重、查询参数归一化和 15 秒结果缓存，能最快拉平大部分慢接口。',
      },
      {
        id: 'code-api-code',
        type: 'code',
        assistantId: 'code',
        assistantName: '代码助手',
        assistantBadge: '代',
        time: '3 小时前',
        fileName: 'api-performance.patch.ts',
        language: 'ts',
        tag: '候选方案',
        code: `export async function requestWithCache(key: string, request: () => Promise<any>) {\n  const hit = responseCache.get(key)\n  if (hit) return hit\n\n  const result = await request()\n  responseCache.set(key, result, 15_000)\n  return result\n}`,
      },
      {
        id: 'code-api-summary',
        type: 'text',
        assistantId: 'code',
        assistantName: '代码助手',
        assistantBadge: '代',
        time: '刚刚',
        content: '下一步建议在 /api/report/summary 上先灰度验证缓存命中率，再决定是否引入更重的批量聚合层。',
        tone: 'subtle',
      },
    ],
    workspaceFiles: [
      { id: 'code-api-root', name: '~/Projects/web-app/src/services/api', type: 'folder', indent: 0, expanded: true },
      { id: 'code-api-client', name: 'request.ts', type: 'file', indent: 1, status: '已扫描' },
      { id: 'code-api-patch', name: 'api-performance.patch.ts', type: 'file', indent: 1, highlighted: true, status: '更新中' },
      { id: 'code-api-report', name: 'api-benchmark.md', type: 'file', indent: 1, status: '已读取' },
    ],
    artifacts: [
      { id: 'code-api-artifact-1', name: 'api-performance.patch.ts', summary: '缓存与参数归一化的候选补丁。', tag: '更新中', tagTone: 'primary' },
      { id: 'code-api-artifact-2', name: 'api-benchmark.md', summary: '当前慢接口耗时和调用链路整理。', tag: '已读取', tagTone: 'neutral' },
    ],
  },
  'code-bug': {
    promptTitle: '继续排查这个 Bug',
    promptDescription: '把常见后续动作放在回复末尾，便于快速推进排查。',
    options: [
      { id: 'summary', title: '总结当前问题', description: '回看原因、影响面和下一步。' },
      { id: 'patch', title: '给出修复建议', description: '直接输出补丁方向和验证点。' },
    ],
    id: 'code-bug',
    mode: 'regular',
    headerTitle: 'Bug 修复追踪',
    headerTag: '待命',
    headerBadge: '代',
    assistantName: '代码助手',
    confirmLabel: '提交参数',
    inputPlaceholder: '输入更多上下文，例如报错场景、预期修复方式或相关文件路径…',
    attachments: ['error-log.txt'],
    workspacePath: '~/Projects/web-app/src/views/Login',
    workspacePreview: {
      kind: 'code',
      fileName: 'login-actions.ts',
      status: '更新中',
      title: '候选修复代码',
      language: 'ts',
      code: `export function resolveButtonState(loading: boolean, valid: boolean) {\n  if (loading) return 'loading'\n  if (!valid) return 'disabled'\n  return 'ready'\n}\n\nexport function resolveButtonTone(hasError: boolean) {\n  return hasError ? 'critical' : 'primary'\n}`,
    },
    messages: [
      {
        id: 'code-bug-user',
        role: 'user',
        content: '帮我查一下最近这个登录页按钮状态切换为什么不对。',
      },
    ],
    chatCards: [
      {
        id: 'code-bug-text',
        type: 'text',
        assistantId: 'code',
        assistantName: '代码助手',
        assistantBadge: '代',
        time: '昨天',
        content: '我会先补齐必要参数，再扫描相关文件并输出修复建议。',
      },
      {
        id: 'code-bug-param',
        type: 'param-form',
        assistantId: 'code',
        assistantName: '代码助手',
        assistantBadge: '代',
        time: '昨天',
        title: '缺少必要参数',
        description: '继续排查前，请补充问题发生日期和优先排查方向。',
        confirmLabel: '提交参数',
        fields: [
          { id: 'date', label: '发生日期', required: true, type: 'date' },
          {
            id: 'scope',
            label: '优先排查方向',
            type: 'choice',
            choices: [
              { id: 'layout', label: '布局样式' },
              { id: 'form', label: '表单反馈' },
              { id: 'state', label: '状态切换' },
            ],
          },
        ],
      },
      {
        id: 'code-bug-tools',
        type: 'tool-call-list',
        assistantId: 'code',
        assistantName: '代码助手',
        assistantBadge: '代',
        time: '刚刚',
        summary: '补齐参数后，代码助手会继续扫描登录页相关文件。',
        calls: [
          {
            name: 'scan_component_tree',
            arg: 'src/views/Login',
            status: 'done',
            duration: '0.9s',
            detail: '扫描登录页按钮状态、表单校验与 loading 链路。',
            result: '发现按钮禁用态与 loading 态未共用状态源。',
            steps: ['遍历登录页组件', '查找按钮状态源', '比对视觉态映射'],
          },
          {
            name: 'build_fix_patch',
            arg: 'button state + loading style',
            status: 'running',
            detail: '正在整理按钮禁用态与加载态补丁。',
            steps: ['统一状态布尔值', '修正按钮样式类', '补充空态说明'],
          },
        ],
      },
      {
        id: 'code-bug-code',
        type: 'code',
        assistantId: 'code',
        assistantName: '代码助手',
        assistantBadge: '代',
        time: '刚刚',
        fileName: 'login-actions.ts',
        language: 'ts',
        tag: '候选修复',
        code: `export function resolveButtonState(loading: boolean, valid: boolean) {\n  if (loading) return 'loading'\n  if (!valid) return 'disabled'\n  return 'ready'\n}`,
      },
      {
        id: 'code-bug-preview',
        type: 'text',
        assistantId: 'code',
        assistantName: '代码助手',
        assistantBadge: '代',
        time: '刚刚',
        content: '我建议先收敛按钮的 ready / loading / disabled 三态，再同步检查 hover 和 focus-visible 的样式映射。',
        tone: 'subtle',
      },
    ],
    workspaceFiles: [
      { id: 'code-root', name: '~/Projects/web-app/src/views/Login', type: 'folder', indent: 0, expanded: true },
      { id: 'code-index', name: 'index.vue', type: 'file', indent: 1, status: '待优化' },
      { id: 'code-style', name: 'login.scss', type: 'file', indent: 1, status: '待优化' },
      { id: 'code-actions', name: 'login-actions.ts', type: 'file', indent: 1, highlighted: true, status: '更新中' },
    ],
    artifacts: [
      { id: 'code-note', name: 'login-redesign.md', summary: '登录页问题分析与视觉修复建议。', tag: '待生成', tagTone: 'primary' },
      { id: 'code-patch', name: 'login-actions.ts', summary: '按钮状态与交互反馈的候选修复逻辑。', tag: '更新中', tagTone: 'primary' },
    ],
  },
  'data-growth': {
    promptTitle: '继续增长分析会话',
    promptDescription: '把后续分析方向放在回复末尾，减少 placeholder 负担。',
    options: [
      { id: 'summary', title: '总结核心结论', description: '提炼关键增长变化和异常点。' },
      { id: 'report', title: '生成汇报版本', description: '整理成适合分享的周报内容。' },
    ],
    id: 'data-growth',
    mode: 'regular',
    headerTitle: '用户增长报告',
    headerTag: '待命',
    headerBadge: '数',
    assistantName: '数据分析师',
    confirmLabel: '确认分析路径',
    inputPlaceholder: '输入补充口径，例如留存口径、投放渠道或希望重点关注的异常…',
    attachments: ['growth_events.csv', 'campaign_cost.xlsx'],
    workspacePath: '~/Projects/data/growth',
    workspacePreview: {
      kind: 'summary',
      fileName: 'growth_weekly_report.md',
      status: '生成中',
      title: '用户增长周报',
      items: [
        { label: '新增用户', value: '本周新增 18,420，环比 +12.6%', tone: 'success' },
        { label: '激活转化', value: '注册到激活转化率 31.4%，比上周下降 2.1%', tone: 'danger' },
        { label: '高价值渠道', value: '企业微信裂变与 SEO 自然流量贡献最大', tone: 'default' },
      ],
    },
    messages: [
      {
        id: 'data-growth-user',
        role: 'user',
        content: '把最近一周的用户增长情况整理成一份可分享的周报，重点说明高价值渠道和激活转化变化。',
      },
    ],
    chatCards: [
      {
        id: 'data-growth-thinking',
        type: 'thinking',
        assistantId: 'data',
        assistantName: '数据分析师',
        assistantBadge: '数',
        time: '2 天前',
        title: '正在思考',
        description: '先对齐新增、激活、留存三个口径，再汇总渠道分层和异常波动原因。',
      },
      {
        id: 'data-growth-tools',
        type: 'tool-call-list',
        assistantId: 'data',
        assistantName: '数据分析师',
        assistantBadge: '数',
        time: '2 天前',
        summary: '数据分析师正在读取增长事件表和投放成本表。',
        calls: [
          {
            name: 'read_file',
            arg: 'growth_events.csv',
            status: 'done',
            duration: '1.0s',
            detail: '读取增长事件并对齐新增、激活、留存口径。',
            result: '识别出 3 段新增峰值与 1 段留存波动。',
            steps: ['读取增长事件表', '统一指标口径', '抽取异常波动段'],
          },
          {
            name: 'read_file',
            arg: 'campaign_cost.xlsx',
            status: 'done',
            duration: '0.7s',
            detail: '补充投放渠道成本与转化效率。',
            result: '发现信息流渠道 CPA 较上周上升 14%。',
            steps: ['读取投放成本表', '关联渠道维度', '计算成本波动'],
          },
          {
            name: 'compose_weekly_report',
            arg: 'growth_weekly_report.md',
            status: 'running',
            detail: '正在生成增长周报和漏斗变化总结。',
            steps: ['汇总关键指标', '生成漏斗观察', '输出周报草稿'],
          },
        ],
      },
      {
        id: 'data-growth-options',
        type: 'choice-form',
        assistantId: 'data',
        assistantName: '数据分析师',
        assistantBadge: '数',
        time: '2 天前',
        title: '这份增长报告优先强调什么？',
        description: '我会根据你的选择调整周报结构和图表占比',
        confirmLabel: '确认分析路径',
        options: [
          { id: 'channel', label: '渠道贡献对比', description: '突出自然流量、投放渠道和裂变渠道贡献' },
          { id: 'funnel', label: '转化漏斗变化', description: '聚焦注册、激活、留存的转换损耗' },
          { id: 'retention', label: '留存与活跃趋势', description: '从长期价值视角看用户质量' },
        ],
      },
      {
        id: 'data-growth-text',
        type: 'text',
        assistantId: 'data',
        assistantName: '数据分析师',
        assistantBadge: '数',
        time: '刚刚',
        content: '目前最值得在周报里强调的是：新增用户仍在增长，但激活转化开始下滑，说明首日体验或渠道质量出现了波动。',
      },
    ],
    workspaceFiles: [
      { id: 'growth-root', name: '~/Projects/data/growth', type: 'folder', indent: 0, expanded: true },
      { id: 'growth-events', name: 'growth_events.csv', type: 'file', indent: 1, status: '已读取' },
      { id: 'growth-cost', name: 'campaign_cost.xlsx', type: 'file', indent: 1, status: '已读取' },
      { id: 'growth-report', name: 'growth_weekly_report.md', type: 'file', indent: 1, highlighted: true, status: '生成中' },
    ],
    artifacts: [
      { id: 'growth-report-artifact', name: 'growth_weekly_report.md', summary: '用户增长周报草稿，包含渠道贡献和激活转化摘要。', tag: '生成中', tagTone: 'primary' },
      { id: 'growth-sheet-artifact', name: 'channel_breakdown.csv', summary: '按渠道拆分的新增与成本明细表。', tag: '已整理', tagTone: 'neutral' },
    ],
  },
  'audit-collab': {
    promptTitle: '继续多助手协作',
    promptDescription: '通用协作追问放在回复末尾，方便随时拉起下一步。',
    options: [
      { id: 'summary', title: '同步当前协作结论', description: '快速汇总各助手当前进度。' },
      { id: 'finance', title: '@财务助手补充', description: '继续拉起财务侧视角。' },
    ],
    id: 'audit-collab',
    mode: 'group',
    headerTitle: '年报审计协作',
    headerTag: '群聊',
    headerBadge: '协',
    assistantName: '多助手协作',
    participantAssistantIds: ['finance', 'code'],
    confirmLabel: '发起协作',
    inputPlaceholder: '输入任务，或使用 @ 提及某个助手加入本次协作…',
    attachments: ['audit-review.zip'],
    workspacePath: '~/Projects/finance/audit',
    workspacePreview: {
      kind: 'summary',
      fileName: 'review-checklist.md',
      status: '协作中',
      title: '协作进度概览',
      items: [
        { label: '财务侧', value: '已完成超支与收入确认初筛', tone: 'success' },
        { label: '代码侧', value: '正在检查导出接口权限与一致性', tone: 'default' },
        { label: '审批项', value: '待确认是否执行修复补丁', tone: 'danger' },
      ],
    },
    messages: [
      {
        id: 'audit-user',
        role: 'user',
        content: '发起年报审计协作，请财务和代码助手一起检查风险点。',
      },
    ],
    chatCards: [
      {
        id: 'audit-finance-note',
        type: 'text',
        assistantId: 'finance',
        assistantName: '财务助手',
        assistantBadge: '财',
        time: '09:14',
        content: '财务侧已完成初步梳理，发现市场费用超支和收入确认节奏需要继续核查。',
      },
      {
        id: 'audit-finance-tools',
        type: 'tool-call-list',
        assistantId: 'finance',
        assistantName: '财务助手',
        assistantBadge: '财',
        time: '09:15',
        calls: [
          {
            name: 'read_file',
            arg: 'annual_report_2023.xlsx',
            status: 'done',
            duration: '0.8s',
            detail: '读取年报财务表并标记超支与收入确认节点。',
            result: '市场费用超支 18.7%，收入确认节奏存在延后迹象。',
            steps: ['读取年报总表', '抽取费用波动项', '标记待复核字段'],
          },
        ],
      },
      {
        id: 'audit-code-note',
        type: 'text',
        assistantId: 'code',
        assistantName: '代码助手',
        assistantBadge: '代',
        time: '09:17',
        content: '我正在同步检查 finance_service.ts 和导出链路的权限判断，确认前后端口径是否一致。',
      },
      {
        id: 'audit-code-tools',
        type: 'tool-call-list',
        assistantId: 'code',
        assistantName: '代码助手',
        assistantBadge: '代',
        time: '09:17',
        calls: [
          {
            name: 'scan_api_consistency',
            arg: 'finance_service.ts',
            status: 'running',
            detail: '核对导出接口与权限校验是否前后一致。',
            steps: ['扫描导出链路', '对比服务端鉴权', '评估补丁影响面'],
          },
        ],
      },
      {
        id: 'audit-approval',
        type: 'approval',
        assistantId: 'code',
        assistantName: '代码助手',
        assistantBadge: '代',
        time: '09:18',
        title: '执行审批',
        description: '检测到 /api/finance/export 存在未授权写入风险，是否允许执行修复补丁？',
        levelTag: '敏感操作',
        actions: ['拒绝', '允许执行', '始终允许'],
      },
    ],
    workspaceFiles: [
      { id: 'audit-root', name: '~/Projects/finance/audit', type: 'folder', indent: 0, expanded: true },
      { id: 'audit-checklist', name: 'review-checklist.md', type: 'file', indent: 1, highlighted: true, status: '协作中' },
      { id: 'audit-note', name: 'handoff-note.docx', type: 'file', indent: 1, status: '待更新' },
    ],
    artifacts: [
      { id: 'audit-checklist-artifact', name: 'review-checklist.md', summary: '汇总当前待办、风险点和联调前检查项。', tag: '协作中', tagTone: 'primary' },
      { id: 'audit-handoff-artifact', name: 'handoff-note.docx', summary: '交付后端联调和验收的说明文档。', tag: '待更新', tagTone: 'neutral' },
    ],
  },
}
